export const STORE_ITEMS_CATALOG = {
  boosts: [
    {
      id: 'boost_1h',
      name: 'Vibe Boost (1 hour)',
      description: 'Make your vibe visible to 3× more people for 1 hour',
      type: 'boost' as const,
      price: 200,
      currency: 'coins' as const,
      icon: '🚀',
      effectDuration: 3600,
    },
    {
      id: 'boost_24h',
      name: 'Vibe Boost (24 hours)',
      description: 'Featured visibility for a full day',
      type: 'boost' as const,
      price: 1200,
      currency: 'coins' as const,
      icon: '⭐',
      effectDuration: 86400,
    },
  ],
  profileFrames: [
    {
      id: 'frame_silver',
      name: 'Silver Frame',
      description: 'Show off your Silver tier status',
      type: 'profile_frame' as const,
      price: 300,
      currency: 'coins' as const,
      icon: '🥈',
      rarity: 'rare' as const,
    },
    {
      id: 'frame_gold',
      name: 'Gold Frame',
      description: 'Exclusive Gold tier border',
      type: 'profile_frame' as const,
      price: 500,
      currency: 'coins' as const,
      icon: '🥇',
      rarity: 'epic' as const,
    },
    {
      id: 'frame_platinum',
      name: 'Platinum Frame',
      description: 'Elite Platinum animated frame',
      type: 'profile_frame' as const,
      price: 700,
      gemPrice: 50,
      currency: 'both' as const,
      icon: '💎',
      rarity: 'legendary' as const,
    },
  ],
  cosmetics: [
    {
      id: 'theme_sunset',
      name: 'Sunset Theme',
      description: 'Warm sunset gradient for your vibes',
      type: 'cosmetic' as const,
      price: 150,
      currency: 'coins' as const,
      icon: '🌅',
      rarity: 'common' as const,
    },
    {
      id: 'theme_ocean',
      name: 'Ocean Theme',
      description: 'Calming ocean waves theme',
      type: 'cosmetic' as const,
      price: 250,
      currency: 'coins' as const,
      icon: '🌊',
      rarity: 'rare' as const,
    },
    {
      id: 'theme_galaxy',
      name: 'Galaxy Theme',
      description: 'Cosmic galaxy theme with stars',
      type: 'cosmetic' as const,
      price: 500,
      gemPrice: 25,
      currency: 'both' as const,
      icon: '🌌',
      rarity: 'epic' as const,
    },
  ],
  skipTokens: [
    {
      id: 'skip_token',
      name: 'Challenge Skip Token',
      description: 'Skip a challenge and still claim rewards',
      type: 'skip_token' as const,
      price: 100,
      currency: 'coins' as const,
      icon: '⏭️',
      rarity: 'common' as const,
    },
  ],
  gifts: [
    {
      id: 'rose',
      name: 'Rose',
      description: 'Send a rose to show appreciation',
      type: 'gift' as const,
      price: 10,
      currency: 'coins' as const,
      icon: '🌹',
    },
    {
      id: 'star',
      name: 'Star',
      description: 'Make someone feel special with a star',
      type: 'gift' as const,
      price: 25,
      currency: 'coins' as const,
      icon: '⭐',
    },
    {
      id: 'crown',
      name: 'Crown',
      description: 'Crown someone as royalty',
      type: 'gift' as const,
      price: 200,
      currency: 'coins' as const,
      icon: '👑',
      rarity: 'legendary' as const,
    },
  ],
};

export const SURPRISE_BOXES = {
  small: {
    id: 'box_small',
    name: 'Small Box',
    type: 'small' as const,
    cost: 0,
    costCurrency: 'free' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 10, maxAmount: 50, rarity: 'common' as const, dropRate: 0.6 },
      { type: 'xp' as const, minAmount: 5, maxAmount: 30, rarity: 'common' as const, dropRate: 0.3 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'rare' as const, dropRate: 0.1, itemId: 'lucky_opener' },
    ],
    dailyLimit: 3,
  },
  lucky: {
    id: 'box_lucky',
    name: 'Lucky Box',
    type: 'lucky' as const,
    cost: 100,
    costCurrency: 'coins' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 100, maxAmount: 500, rarity: 'rare' as const, dropRate: 0.4 },
      { type: 'xp' as const, minAmount: 50, maxAmount: 200, rarity: 'rare' as const, dropRate: 0.3 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'epic' as const, dropRate: 0.2, itemId: 'rare_collector' },
      { type: 'item' as const, minAmount: 1, maxAmount: 1, rarity: 'legendary' as const, dropRate: 0.1, itemId: 'theme_galaxy' },
    ],
    dailyLimit: 10,
  },
  premium: {
    id: 'box_premium',
    name: 'Premium Box',
    type: 'premium' as const,
    cost: 50,
    costCurrency: 'gems' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 500, maxAmount: 2000, rarity: 'epic' as const, dropRate: 0.3 },
      { type: 'xp' as const, minAmount: 200, maxAmount: 1000, rarity: 'epic' as const, dropRate: 0.2 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'legendary' as const, dropRate: 0.3, itemId: 'premium_collector' },
      { type: 'item' as const, minAmount: 1, maxAmount: 3, rarity: 'legendary' as const, dropRate: 0.2, itemId: 'exclusive_cosmetics' },
    ],
    dailyLimit: 5,
  },
};

export const BADGES_CATALOG = {
  // 🎭 Emotion Badges
  happy_explorer: {
    id: 'happy_explorer',
    name: 'Happy Explorer',
    description: 'Post 5 Happy vibes',
    icon: '😊',
    rarity: 'common' as const,
    category: 'positivity' as const,
    requirement: 'Post 5 Happy vibes',
  },
  emotion_collector: {
    id: 'emotion_collector',
    name: 'Emotion Collector',
    description: 'Try all 8 emotions',
    icon: '🎭',
    rarity: 'rare' as const,
    category: 'achievement' as const,
    requirement: 'Post vibes in all 8 emotions',
  },
  emotion_master: {
    id: 'emotion_master',
    name: 'Emotion Master',
    description: '100+ vibes in each emotion',
    icon: '💎',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: '100+ vibes in each emotion',
  },
  
  // 📍 Location Badges
  neighborhood_hero: {
    id: 'neighborhood_hero',
    name: 'Neighborhood Hero',
    description: 'Top in your area',
    icon: '🏘️',
    rarity: 'rare' as const,
    category: 'city' as const,
    requirement: 'Top contributor in your neighborhood',
  },
  city_champion: {
    id: 'city_champion',
    name: 'City Champion',
    description: '#1 in city this week',
    icon: '🏆',
    rarity: 'epic' as const,
    category: 'city' as const,
    requirement: 'Rank #1 in your city this week',
  },
  national_traveler: {
    id: 'national_traveler',
    name: 'National Traveler',
    description: 'Post from 10+ cities',
    icon: '✈️',
    rarity: 'epic' as const,
    category: 'city' as const,
    requirement: 'Post vibes from 10 different cities',
  },
  
  // 🔥 Streak Badges
  consistent: {
    id: 'consistent',
    name: 'Consistent',
    description: '7 day streak',
    icon: '🔥',
    rarity: 'common' as const,
    category: 'consistency' as const,
    requirement: '7 day posting streak',
  },
  dedicated: {
    id: 'dedicated',
    name: 'Dedicated',
    description: '30 day streak',
    icon: '💪',
    rarity: 'rare' as const,
    category: 'consistency' as const,
    requirement: '30 day posting streak',
  },
  unstoppable: {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: '100 day streak',
    icon: '⚡',
    rarity: 'legendary' as const,
    category: 'consistency' as const,
    requirement: '100 day posting streak',
  },
  
  // 🎊 Festival Badges (Limited Edition)
  diwali_2024_champion: {
    id: 'diwali_2024_champion',
    name: 'Diwali 2024 Champion',
    description: 'Participated in Diwali 2024',
    icon: '🪔',
    rarity: 'epic' as const,
    category: 'seasonal' as const,
    requirement: 'Complete Diwali festival challenge',
  },
  holi_celebration_master: {
    id: 'holi_celebration_master',
    name: 'Holi Celebration Master',
    description: 'Celebrated Holi with vibes',
    icon: '🎨',
    rarity: 'epic' as const,
    category: 'seasonal' as const,
    requirement: 'Complete Holi festival challenge',
  },
  
  // 💪 Challenge Badges
  challenge_starter: {
    id: 'challenge_starter',
    name: 'Challenge Starter',
    description: 'Complete 5 challenges',
    icon: '🎯',
    rarity: 'common' as const,
    category: 'achievement' as const,
    requirement: 'Complete 5 challenges',
  },
  challenge_hunter: {
    id: 'challenge_hunter',
    name: 'Challenge Hunter',
    description: 'Complete 50 challenges',
    icon: '🏹',
    rarity: 'rare' as const,
    category: 'achievement' as const,
    requirement: 'Complete 50 challenges',
  },
  challenge_legend: {
    id: 'challenge_legend',
    name: 'Challenge Legend',
    description: 'Complete 500 challenges',
    icon: '👑',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Complete 500 challenges',
  },
  
  // 👥 Social Badges
  supportive: {
    id: 'supportive',
    name: 'Supportive',
    description: '100 helpful comments',
    icon: '🤝',
    rarity: 'rare' as const,
    category: 'empathy' as const,
    requirement: 'Give 100 helpful comments',
  },
  community_builder: {
    id: 'community_builder',
    name: 'Community Builder',
    description: '1000 reactions given',
    icon: '🌟',
    rarity: 'epic' as const,
    category: 'generosity' as const,
    requirement: 'Give 1000 reactions',
  },
  inspiration: {
    id: 'inspiration',
    name: 'Inspiration',
    description: 'Your vibes got 10k+ views',
    icon: '✨',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Receive 10,000+ total views',
  },
  
  // 🌟 Exclusive Badges (Cannot buy with coins)
  founding_member: {
    id: 'founding_member',
    name: 'Founding Member',
    description: 'Joined in first month',
    icon: '🎖️',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Join during beta or first month',
  },
  beta_tester: {
    id: 'beta_tester',
    name: 'Beta Tester',
    description: 'Active in beta',
    icon: '🧪',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Participate in beta testing',
  },
  top_100: {
    id: 'top_100',
    name: 'Top 100',
    description: 'Leaderboard achievement',
    icon: '💯',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Reach Top 100 on leaderboard',
  },
  staff_favorite: {
    id: 'staff_favorite',
    name: 'Staff Favorite',
    description: 'Curated by team',
    icon: '⭐',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Selected by Vibee OS team',
  },
  
  // Original badges
  helpful_hero: {
    id: 'helpful_hero',
    name: 'Helpful Hero',
    description: 'Earned by getting 10 helpful votes in a week',
    icon: '🦸',
    rarity: 'rare' as const,
    category: 'empathy' as const,
    requirement: 'Get 10 helpful votes in one week',
  },
  city_contributor: {
    id: 'city_contributor',
    name: 'City Contributor',
    description: 'Participated in a city challenge',
    icon: '🏙️',
    rarity: 'common' as const,
    category: 'achievement' as const,
    requirement: 'Complete a city challenge',
  },
  gold_tier_creator: {
    id: 'gold_tier_creator',
    name: 'Gold Tier Creator',
    description: 'Achieved Gold tier status',
    icon: '🥇',
    rarity: 'epic' as const,
    category: 'achievement' as const,
    requirement: 'Reach Gold tier',
  },
  platinum_elite: {
    id: 'platinum_elite',
    name: 'Platinum Elite',
    description: 'Achieved Platinum tier status',
    icon: '💎',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Reach Platinum tier',
  },
  legend_status: {
    id: 'legend_status',
    name: 'Legend',
    description: 'Achieved Legend tier status',
    icon: '👑',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Reach Legend tier',
    meta: {
      animated: true,
      soundEffect: 'fanfare',
    },
  },
  generous_soul: {
    id: 'generous_soul',
    name: 'Generous Soul',
    description: 'Sent 100 gifts to other users',
    icon: '💝',
    rarity: 'epic' as const,
    category: 'generosity' as const,
    requirement: 'Send 100 gifts',
  },
  streak_master: {
    id: 'streak_master',
    name: 'Streak Master',
    description: 'Posted vibes for 30 consecutive days',
    icon: '🔥',
    rarity: 'epic' as const,
    category: 'consistency' as const,
    requirement: '30-day posting streak',
  },
};
