export const STORE_ITEMS_CATALOG = {
  boosts: [
    {
      id: 'boost_1h',
      name: 'Vibe Boost (1 hour)',
      description: 'Make your vibe visible to 3× more people for 1 hour',
      type: 'boost' as const,
      price: 200,
      currency: 'coins' as const,
      icon: '🚀',
      effectDuration: 3600,
    },
    {
      id: 'boost_24h',
      name: 'Vibe Boost (24 hours)',
      description: 'Featured visibility for a full day',
      type: 'boost' as const,
      price: 1200,
      currency: 'coins' as const,
      icon: '⭐',
      effectDuration: 86400,
    },
  ],
  profileFrames: [
    {
      id: 'frame_silver',
      name: 'Silver Frame',
      description: 'Show off your Silver tier status',
      type: 'profile_frame' as const,
      price: 300,
      currency: 'coins' as const,
      icon: '🥈',
      rarity: 'rare' as const,
    },
    {
      id: 'frame_gold',
      name: 'Gold Frame',
      description: 'Exclusive Gold tier border',
      type: 'profile_frame' as const,
      price: 500,
      currency: 'coins' as const,
      icon: '🥇',
      rarity: 'epic' as const,
    },
    {
      id: 'frame_platinum',
      name: 'Platinum Frame',
      description: 'Elite Platinum animated frame',
      type: 'profile_frame' as const,
      price: 700,
      gemPrice: 50,
      currency: 'both' as const,
      icon: '💎',
      rarity: 'legendary' as const,
    },
  ],
  cosmetics: [
    {
      id: 'theme_sunset',
      name: 'Sunset Theme',
      description: 'Warm sunset gradient for your vibes',
      type: 'cosmetic' as const,
      price: 150,
      currency: 'coins' as const,
      icon: '🌅',
      rarity: 'common' as const,
    },
    {
      id: 'theme_ocean',
      name: 'Ocean Theme',
      description: 'Calming ocean waves theme',
      type: 'cosmetic' as const,
      price: 250,
      currency: 'coins' as const,
      icon: '🌊',
      rarity: 'rare' as const,
    },
    {
      id: 'theme_galaxy',
      name: 'Galaxy Theme',
      description: 'Cosmic galaxy theme with stars',
      type: 'cosmetic' as const,
      price: 500,
      gemPrice: 25,
      currency: 'both' as const,
      icon: '🌌',
      rarity: 'epic' as const,
    },
  ],
  skipTokens: [
    {
      id: 'skip_token',
      name: 'Challenge Skip Token',
      description: 'Skip a challenge and still claim rewards',
      type: 'skip_token' as const,
      price: 100,
      currency: 'coins' as const,
      icon: '⏭️',
      rarity: 'common' as const,
    },
  ],
  gifts: [
    {
      id: 'rose',
      name: 'Rose',
      description: 'Send a rose to show appreciation',
      type: 'gift' as const,
      price: 10,
      currency: 'coins' as const,
      icon: '🌹',
    },
    {
      id: 'star',
      name: 'Star',
      description: 'Make someone feel special with a star',
      type: 'gift' as const,
      price: 25,
      currency: 'coins' as const,
      icon: '⭐',
    },
    {
      id: 'crown',
      name: 'Crown',
      description: 'Crown someone as royalty',
      type: 'gift' as const,
      price: 200,
      currency: 'coins' as const,
      icon: '👑',
      rarity: 'legendary' as const,
    },
  ],
};

export const SURPRISE_BOXES = {
  small: {
    id: 'box_small',
    name: 'Small Box',
    type: 'small' as const,
    cost: 0,
    costCurrency: 'free' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 10, maxAmount: 50, rarity: 'common' as const, dropRate: 0.6 },
      { type: 'xp' as const, minAmount: 5, maxAmount: 30, rarity: 'common' as const, dropRate: 0.3 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'rare' as const, dropRate: 0.1, itemId: 'lucky_opener' },
    ],
    dailyLimit: 3,
  },
  lucky: {
    id: 'box_lucky',
    name: 'Lucky Box',
    type: 'lucky' as const,
    cost: 100,
    costCurrency: 'coins' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 100, maxAmount: 500, rarity: 'rare' as const, dropRate: 0.4 },
      { type: 'xp' as const, minAmount: 50, maxAmount: 200, rarity: 'rare' as const, dropRate: 0.3 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'epic' as const, dropRate: 0.2, itemId: 'rare_collector' },
      { type: 'item' as const, minAmount: 1, maxAmount: 1, rarity: 'legendary' as const, dropRate: 0.1, itemId: 'theme_galaxy' },
    ],
    dailyLimit: 10,
  },
  premium: {
    id: 'box_premium',
    name: 'Premium Box',
    type: 'premium' as const,
    cost: 50,
    costCurrency: 'gems' as const,
    possibleRewards: [
      { type: 'coins' as const, minAmount: 500, maxAmount: 2000, rarity: 'epic' as const, dropRate: 0.3 },
      { type: 'xp' as const, minAmount: 200, maxAmount: 1000, rarity: 'epic' as const, dropRate: 0.2 },
      { type: 'badge' as const, minAmount: 1, maxAmount: 1, rarity: 'legendary' as const, dropRate: 0.3, itemId: 'premium_collector' },
      { type: 'item' as const, minAmount: 1, maxAmount: 3, rarity: 'legendary' as const, dropRate: 0.2, itemId: 'exclusive_cosmetics' },
    ],
    dailyLimit: 5,
  },
};

export const BADGES_CATALOG = {
  helpful_hero: {
    id: 'helpful_hero',
    name: 'Helpful Hero',
    description: 'Earned by getting 10 helpful votes in a week',
    icon: '🦸',
    rarity: 'rare' as const,
    category: 'empathy' as const,
    requirement: 'Get 10 helpful votes in one week',
  },
  city_contributor: {
    id: 'city_contributor',
    name: 'City Contributor',
    description: 'Participated in a city challenge',
    icon: '🏙️',
    rarity: 'common' as const,
    category: 'achievement' as const,
    requirement: 'Complete a city challenge',
  },
  gold_tier_creator: {
    id: 'gold_tier_creator',
    name: 'Gold Tier Creator',
    description: 'Achieved Gold tier status',
    icon: '🥇',
    rarity: 'epic' as const,
    category: 'achievement' as const,
    requirement: 'Reach Gold tier',
  },
  platinum_elite: {
    id: 'platinum_elite',
    name: 'Platinum Elite',
    description: 'Achieved Platinum tier status',
    icon: '💎',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Reach Platinum tier',
  },
  legend_status: {
    id: 'legend_status',
    name: 'Legend',
    description: 'Achieved Legend tier status',
    icon: '👑',
    rarity: 'legendary' as const,
    category: 'achievement' as const,
    requirement: 'Reach Legend tier',
    meta: {
      animated: true,
      soundEffect: 'fanfare',
    },
  },
  generous_soul: {
    id: 'generous_soul',
    name: 'Generous Soul',
    description: 'Sent 100 gifts to other users',
    icon: '💝',
    rarity: 'epic' as const,
    category: 'generosity' as const,
    requirement: 'Send 100 gifts',
  },
  streak_master: {
    id: 'streak_master',
    name: 'Streak Master',
    description: 'Posted vibes for 30 consecutive days',
    icon: '🔥',
    rarity: 'epic' as const,
    category: 'consistency' as const,
    requirement: '30-day posting streak',
  },
};
